providers = ["python"]

[phases.setup]
aptPkgs = ["libmysqlclient-dev", "libssl-dev", "libmysqlcppconn-dev", "python3-pip", "build-essential", "python3-dev", "libffi-dev", "libsm6", "libxrender1", "libfontconfig1", "libice6", "pkg-config", "libgtk2.0-dev"]